import {migrate,iso,parseDate,monday,add,hours,dailyTotal,validateSlot,validDate,appendSlot,ensureUnlocked,overlaps,companySnapshot,switchCompany} from './core.mjs';
import {createTimesheetPdf} from './pdf.mjs';
import {submissionSchedule} from './automation.mjs';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STORAGE='gradcon-timesheet-v2',LEGACY='gradcon-timesheet-v1';
let state,storageError=false;
try{state=migrate(JSON.parse(localStorage.getItem(STORAGE)||localStorage.getItem(LEGACY)||'null'));}catch{state=migrate(null);storageError=true;}
let selected=monday(new Date()),editing=null,newEmployer=false,pendingLogo='';
const fmt=(d,options={day:'numeric',month:'short'})=>d.toLocaleDateString('en-AU',options),slots=date=>state.entries[date]||[];
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),4000);}
function persist(next,redraw=true){if(storageError)throw Error('Stored data could not be read. Please allow browser storage and reload before saving.');localStorage.setItem(STORAGE,JSON.stringify(next));state=next;if(redraw)render();}
function transact(action){try{action();}catch(e){toast(e.message||'Unable to save. Your existing data has not changed.');}}
function weekSlots(){return Array.from({length:7},(_,i)=>slots(iso(add(selected,i)))).flat();}
function getStatus(){if(state.submitted[iso(selected)])return 'Submitted';return iso(new Date())>=iso(add(selected,8))?'Ready to submit':'In progress';}
function render(){
 document.body?.setAttribute?.('data-theme',state.settings.theme||'blue');document.body?.setAttribute?.('data-density',state.settings.density||'comfortable');

 const profiles={...state.companies,[state.activeCompany]:companySnapshot(state)};
 $('companySelect').innerHTML=Object.entries(profiles).map(([id,c])=>'<option value="'+esc(id)+'"'+(id===state.activeCompany?' selected':'')+'>'+esc(c.settings.employer||'Untitled employer')+'</option>').join('');
 $('companyTag').textContent=state.settings.tag||'';
 $('companyLogo').innerHTML=/^data:image\/(png|jpeg);base64,/.test(state.settings.logo||'')?'<img alt="Company logo" src="'+esc(state.settings.logo)+'">':'<span aria-label="No company logo uploaded">🏡</span>';

 const scheduled=submissionSchedule(state,selected);const sun=add(selected,6),entries=weekSlots(),total=dailyTotal(entries),locked=!!state.submitted[iso(selected)];
 $('weekTitle').textContent=fmt(selected)+' – '+fmt(sun,{day:'numeric',month:'short',year:'numeric'});
 $('ending').textContent=fmt(sun,{weekday:'short',day:'numeric',month:'short'});$('submission').textContent=fmt(parseDate(scheduled.date),{weekday:'short',day:'numeric',month:'short'})+' · '+scheduled.time;$('payment').textContent=fmt(add(selected,9),{weekday:'short',day:'numeric',month:'short'});
 $('totalHours').innerHTML=total.toFixed(2)+' <small>hrs</small>';$('totalDetail').textContent=entries.length+' time '+(entries.length===1?'slot':'slots')+' recorded';$('footerTotal').textContent=total.toFixed(2)+' hours';$('status').textContent=getStatus();$('status').className='badge'+(locked?' submitted':'');$('submitBtn').textContent=locked?'Reopen timesheet':'Mark as submitted';$('copyWeek').disabled=locked;$('addEntry').disabled=locked;
 $('days').innerHTML=Array.from({length:7},(_,i)=>{
 const d=add(selected,i),key=iso(d),list=slots(key),today=key===iso(new Date());
 return '<section class="day'+(today?' today':'')+'"><div class="day-date"><strong>'+fmt(d,{weekday:'short'})+'</strong><small>'+fmt(d)+'</small>'+(today?'<span class="today-label">TODAY</span>':'')+'</div><div class="slots">'+list.map(e=>'<button class="slot" data-date="'+key+'" data-id="'+esc(e.id)+'"'+(locked?' disabled':'')+' aria-label="Edit time slot '+esc(e.start||'manual')+' on '+key+'"><span><span class="slot-time">'+esc(e.start&&e.finish?e.start+' – '+e.finish:e.kind==='summary'?'Daily summary':'Manual hours')+(e.start&&e.finish&&e.finish<e.start?' <small>(+1 day)</small>':'')+'</span><span class="slot-meta">'+esc([e.site,e.notes].filter(Boolean).join(' · '))+'</span></span><span class="slot-right">'+hours(e).toFixed(2)+' h'+(e.kind!=='summary'&&e.manual!==''&&e.manual!=null?' · override':'')+' &nbsp; ›</span></button>').join('')+(!list.length?'<div class="noentry">No hours recorded</div>':'')+(!locked?'<button class="add-slot" data-date="'+key+'">＋ Add hours</button>':'')+'<label class="day-note">📝 Day notes<textarea data-day-note="'+key+'" maxlength="3000" placeholder="Site updates, achievements, or anything to remember…"'+(locked?' disabled':'')+'>'+esc(state.dayNotes?.[key]||'')+'</textarea></label><label class="note-toggle"><input type="checkbox" data-note-include="'+key+'"'+(state.dayNotesIncluded?.[key]?' checked':'')+(locked?' disabled':'')+'> Include day notes in PDF</label></div><div class="daytotal">'+(list.length?dailyTotal(list).toFixed(2):'—')+'<small>hours</small></div></section>';
 }).join('');
 const s=state.settings;for(const id of ['legal','abn','location','phone','email'])$(id).textContent=s[id];$('employerName').textContent=s.employer;$('profileBtn').textContent=s.name?s.name.split(/\s+/).map(n=>n[0]).slice(0,2).join('').toUpperCase():'G';
}
function openEntry(date,id=null){try{ensureUnlocked(state,date);}catch(e){toast(e.message);return;}editing=id?{date,id}:null;const e=id?slots(date).find(e=>e.id===id):{};if(!e)return;$('entryTitle').textContent=id?'Edit hours':'Add hours';$('entryDate').value=date;for(const field of ['start','finish','manual','site','notes'])$(field).value=e[field]??'';$('entryError').textContent='';$('deleteSlot').hidden=!id;$('modeSummary').checked=e.kind==='summary';$('modeSplit').checked=!$('modeSummary').checked;syncMode();$('entryDialog').showModal();}
function draft(){const summary=$('modeSummary').checked;return {date:$('entryDate').value,kind:summary?'summary':'split',start:summary?'':$('start').value,finish:summary?'':$('finish').value,manual:$('manual').value,site:$('site').value.trim(),notes:$('notes').value.trim()};}
function updateCalculation(){const d=draft();$('calculation').textContent=(d.manual!==''||(d.start&&d.finish))?hours(d).toFixed(2)+' hours'+(d.finish&&d.start&&d.finish<d.start?' · Finishes the next day':''):'Enter start and finish times.';}
for(const field of ['start','finish','manual'])$(field).addEventListener('input',updateCalculation);
function saveSlot(data,old=null,replaceDay=false){
 validateSlot(data);ensureUnlocked(state,data.date);if(old)ensureUnlocked(state,old.date);

 const next=structuredClone(state);if(old)next.entries[old.date]=slots(old.date).filter(e=>e.id!==old.id);
 if(replaceDay)next.entries[data.date]=[];
 if((next.entries[data.date]||[]).some(e=>e.kind==='summary')||(data.kind==='summary'&&(next.entries[data.date]||[]).length))throw Error('Switch this day’s entry mode in the editor before adding hours.');
 if(overlaps(next,data.date,data,old?.id))throw Error('This time overlaps an existing slot. Adjust the times to avoid counting hours twice.');
 const {date,...entry}=data;entry.id=old?.id||crypto.randomUUID();next.entries[date]=[...(next.entries[date]||[]),entry].sort((a,b)=>(a.start||'').localeCompare(b.start||''));persist(next);return entry;
}
function submitEntry(event){event.preventDefault();try{const d=draft();validateSlot(d);ensureUnlocked(state,d.date);if(editing)ensureUnlocked(state,editing.date);const other=slots(d.date).filter(e=>e.id!==editing?.id);const replace=d.kind==='summary'?other.length>0:other.some(e=>e.kind==='summary');if(replace&&!confirm('Replace existing entries for this day with '+(d.kind==='summary'?'one daily summary':'split time slots')+'? This prevents double counting.'))return;saveSlot(d,editing,replace);selected=monday(parseDate(d.date));render();$('entryDialog').close();toast('Time slot saved');}catch(e){$('entryError').textContent=e.message;}}
function deleteEntry(){if(!editing)return;if(!confirm('Delete this time slot? Other slots on this day will be kept.'))return;transact(()=>{ensureUnlocked(state,editing.date);const next=structuredClone(state);next.entries[editing.date]=slots(editing.date).filter(e=>e.id!==editing.id);persist(next);$('entryDialog').close();toast('Time slot deleted');});}
const settingsFields=[['name','Your name'],['employee','Employee / contractor no.'],['employer','Employer display name'],['legal','Legal entity'],['abn','ABN'],['phone','Phone'],['email','Email'],['location','Location'],['tag','Company tag'],['sender','Sender email'],['recipient','Accounts email(s)'],['bcc','BCC email(s) — optional']];
const pdfFields=[['logo','Company logo'],['employer','Employer name'],['legal','Legal name and ABN'],['employee','Employee / contractor number'],['schedule','Submission and payment dates'],['times','Start and finish times'],['sites','Site / job names'],['slotNotes','Slot descriptions / notes'],['dayNotes','Day notes marked for inclusion'],['signature','Approval / signature line']];
function openSettings(){newEmployer=false;showSettings(state.settings);}
function showSettings(values){pendingLogo=values.logo||'';$('scheduleDay').value=String(values.schedule?.weekday??2);$('scheduleTime').value=values.schedule?.time||'23:00';$('fallbackHours').value=values.schedule?.fallbackHours??6;$('scheduleDate').value=newEmployer?'':state.scheduleOverrides?.[iso(selected)]||'';$('pdfOptions').innerHTML=pdfFields.map(([key,label])=>'<label class="pref-toggle"><input type="checkbox" id="pdf-'+key+'"'+(values.pdf?.[key]!==false?' checked':'')+'> '+label+'</label>').join('');$('themeChoice').value=values.theme||'blue';$('densityChoice').value=values.density||'comfortable';$('logoUpload').value='';$('logoStatus').textContent=pendingLogo?'Logo attached':'Upload your company’s actual logo, or add it later.';$('settingsFields').innerHTML=settingsFields.map(([key,label])=>'<label>'+label+'<input name="'+key+'" id="setting-'+key+'" type="'+(['email','sender','recipient','bcc'].includes(key)?'email':'text')+'"'+(['recipient','bcc'].includes(key)?' multiple':'')+' maxlength="300" value="'+esc(values[key]||'')+'"'+(['employer','sender','recipient'].includes(key)?' required':'')+'></label>').join('');$('settingsDialog').showModal();}
function saveSettings(e){e.preventDefault();transact(()=>{const next=structuredClone(state);if(newEmployer){next.companies[next.activeCompany]=companySnapshot(next);next.activeCompany=crypto.randomUUID();next.settings={};next.entries={};next.submitted={};next.dayNotes={};next.dayNotesIncluded={};next.history=[];next.scheduleOverrides={};}for(const [key] of settingsFields)next.settings[key]=$('setting-'+key).value.trim();next.settings.logo=pendingLogo;next.settings.pdf=Object.fromEntries(pdfFields.map(([key])=>[key,$('pdf-'+key).checked]));next.settings.theme=$('themeChoice').value;next.settings.density=$('densityChoice').value;next.settings.schedule={requested:true,weekday:Number($('scheduleDay').value),time:$('scheduleTime').value,timezone:'Australia/Melbourne',fallbackHours:Number($('fallbackHours').value)};next.scheduleOverrides??={};if($('scheduleDate').value)next.scheduleOverrides[iso(selected)]=$('scheduleDate').value;else delete next.scheduleOverrides[iso(selected)];persist(next);newEmployer=false;$('settingsDialog').close();toast('Employer details saved');});}
$('newCompany').onclick=()=>{newEmployer=true;showSettings({name:state.settings.name,employee:state.settings.employee,sender:state.settings.sender,bcc:state.settings.bcc});};
$('companySelect').onchange=e=>transact(()=>persist(switchCompany(state,e.target.value)));
$('removeLogo').onclick=()=>{pendingLogo='';$('logoUpload').value='';$('logoStatus').textContent='Logo removed. Save details to confirm.';};
$('logoUpload').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!['image/png','image/jpeg'].includes(file.type)||file.size>1024*1024){toast('Choose a PNG or JPEG under 1 MB.');return;}try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=data;});const canvas=document.createElement('canvas'),scale=Math.min(1,512/Math.max(img.width,img.height));canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);pendingLogo=canvas.toDataURL('image/png');$('logoStatus').textContent='Logo ready. Save details to confirm.';}catch{toast('This image could not be opened. Try another PNG or JPEG.');}};
$('days').addEventListener('change',e=>{const date=e.target.dataset?.dayNote||e.target.dataset?.noteInclude;if(!date)return;transact(()=>{ensureUnlocked(state,date);const next=structuredClone(state);if(e.target.dataset.noteInclude){next.dayNotesIncluded??={};next.dayNotesIncluded[date]=e.target.checked;}else{next.dayNotes[date]=e.target.value.trim();}persist(next,false);toast('Day note preferences saved');});});
function copyPrevious(){transact(()=>{
 const previous=Array.from({length:7},(_,i)=>slots(iso(add(selected,i-7))));if(!previous.flat().length){toast('No time slots in the previous week.');return;}
 if(weekSlots().length&&!confirm('Replace all time slots in this week with the previous week?'))return;
 const next=structuredClone(state);for(let i=0;i<7;i++){const key=iso(add(selected,i));ensureUnlocked(state,key);next.entries[key]=previous[i].map(e=>({...e,id:crypto.randomUUID()}));}
 for(let i=0;i<7;i++){const key=iso(add(selected,i));for(const e of next.entries[key])if(overlaps(next,key,e,e.id))throw Error('Copy would create overlapping slots, including an overnight slot. Edit the affected days individually.');}
 persist(next);toast('Previous week copied');
 });}
function markSubmitted(){transact(()=>{const key=iso(selected),next=structuredClone(state);if(next.submitted[key]){if(!confirm('Reopen this submitted timesheet for editing?'))return;delete next.submitted[key];}else{if(!weekSlots().length){toast('Add a time slot before marking this week as submitted.');return;}if(!confirm('Mark this week as submitted? This records its status; it does not send an email.'))return;next.submitted[key]=true;next.history??=[];const snapshot={settings:structuredClone(next.settings),entries:structuredClone(next.entries),dayNotes:structuredClone(next.dayNotes),dayNotesIncluded:structuredClone(next.dayNotesIncluded),scheduleOverrides:structuredClone(next.scheduleOverrides)};next.history.push({id:crypto.randomUUID(),week:key,savedAt:new Date().toISOString(),revision:next.history.filter(h=>h.week===key).length+1,snapshot});}persist(next);toast(next.submitted[key]?'Marked as submitted':'Timesheet reopened');});}
function buildPrint(){
 const s=state.settings,sun=add(selected,6);let rows='';
 for(let i=0;i<7;i++){const d=add(selected,i),list=slots(iso(d));if(!list.length)rows+='<tr><td>'+fmt(d,{weekday:'short',day:'numeric',month:'short'})+'</td><td>—</td><td>—</td><td>—</td><td></td><td></td></tr>';
 for(const e of list)rows+='<tr><td>'+fmt(d,{weekday:'short',day:'numeric',month:'short'})+'</td><td>'+esc(e.start||'—')+'</td><td>'+esc(e.finish||'—')+(e.start&&e.finish&&e.finish<e.start?' (+1 day)':'')+'</td><td>'+hours(e).toFixed(2)+(e.manual!==''&&e.manual!=null?'*':'')+'</td><td>'+esc(e.site)+'</td><td>'+esc(e.notes)+'</td></tr>';
 if(list.length>1)rows+='<tr><td colspan="6" class="day-subtotal">'+fmt(d,{weekday:'long'})+' total: '+dailyTotal(list).toFixed(2)+' hours</td></tr>';
 }
 $('printSheet').innerHTML='<h1>Weekly timesheet</h1><div class="print-sub">'+esc(s.employer)+' · '+esc(s.legal)+'</div><div class="print-meta"><div><b>Employee:</b> '+esc(s.name||'________________')+'</div><div><b>Employee / contractor no.:</b> '+esc(s.employee||'—')+'</div><div><b>Week ending:</b> '+fmt(sun,{weekday:'long',day:'numeric',month:'long',year:'numeric'})+'</div><div><b>ABN:</b> '+esc(s.abn)+'</div><div><b>Submission:</b> '+fmt(add(selected,8),{weekday:'long',day:'numeric',month:'long',year:'numeric'})+'</div><div><b>Payment:</b> '+fmt(add(selected,9),{weekday:'long',day:'numeric',month:'long',year:'numeric'})+'</div></div><table><colgroup><col style="width:17%"><col style="width:10%"><col style="width:13%"><col style="width:9%"><col style="width:20%"><col style="width:31%"></colgroup><thead><tr><th>DATE</th><th>START</th><th>FINISH</th><th>HOURS</th><th>SITE / JOB</th><th>DESCRIPTION / NOTES</th></tr></thead><tbody>'+rows+'</tbody></table><div class="print-total">Total: '+dailyTotal(weekSlots()).toFixed(2)+' hours</div>'+(weekSlots().some(e=>e.manual!==''&&e.manual!=null)?'<p>* Manually adjusted hours.</p>':'')+'<div class="signature">Employee approval / signature: _________________________ &nbsp; Date: ______________</div>';
}
$('days').addEventListener('click',e=>{const b=e.target.closest('button[data-date]');if(b)openEntry(b.dataset.date,b.dataset.id||null);});
$('entryForm').addEventListener('submit',submitEntry);$('deleteSlot').onclick=deleteEntry;$('settingsForm').onsubmit=saveSettings;
for(const id of ['navSettings','profileBtn','editEmployer'])$(id).onclick=openSettings;
$('prevWeek').onclick=()=>{selected=add(selected,-7);render();};$('nextWeek').onclick=()=>{selected=add(selected,7);render();};
for(const id of ['thisWeek','navTimesheets'])$(id).onclick=()=>{selected=monday(new Date());render();};
$('addEntry').onclick=()=>{const today=iso(new Date());openEntry(today>=iso(selected)&&today<=iso(add(selected,6))?today:iso(selected));};
$('copyWeek').onclick=copyPrevious;$('submitBtn').onclick=markSubmitted;$('pdfBtn').onclick=downloadPdf;
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
window.addEventListener('storage',e=>{if(e.key===STORAGE&&e.newValue){if($('entryDialog').open||$('settingsDialog').open){toast('Another tab changed this timesheet. Reload before saving to avoid overwriting changes.');storageError=true;return;}try{state=migrate(JSON.parse(e.newValue));render();}catch{toast('Could not read changes from another tab.');}}});
if(document.modelContext?.registerTool)try{Promise.resolve(document.modelContext.registerTool({name:'add_time_entry',title:'Add time slot',description:'Append one time slot without replacing other slots on that day. Rejects overlapping times and submitted weeks.',inputSchema:{type:'object',properties:{date:{type:'string'},start:{type:'string'},finish:{type:'string'},site:{type:'string'},notes:{type:'string'}},required:['date','start','finish'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||typeof input!=='object')throw Error('A time slot is required.');for(const k of ['date','start','finish'])if(typeof input[k]!=='string')throw Error('Invalid '+k);for(const k of ['site','notes'])if(input[k]!=null&&typeof input[k]!=='string')throw Error('Invalid '+k);const e=saveSlot({...input,manual:'',site:input.site||'',notes:input.notes||''});selected=monday(parseDate(input.date));render();return {saved:true,id:e.id,date:input.date,hours:hours(e)};}})).catch(()=>{});}catch{}
render();if(storageError)toast('Stored data could not be read. Saving is paused to protect your entries.');

function syncMode(){const summary=$('modeSummary').checked;for(const id of ['startLabel','finishLabel'])$(id).hidden=summary;$('manual').required=summary;$('hoursLabel').textContent=summary?'Total hours for the day':'Hours override (optional)';$('manual').placeholder=summary?'e.g. 8':'Calculated automatically';$('modeHint').textContent=summary?'One total for the day. Replaces split slots after confirmation.':'Separate start and finish times for each part of the day.';updateCalculation();}
$('modeSplit').onchange=syncMode;$('modeSummary').onchange=syncMode;
async function downloadPdf(){try{const file=await createTimesheetPdf(state,selected);const url=URL.createObjectURL(new Blob([file.bytes],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=file.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);$('mailFile').textContent='Attach: '+file.filename;toast('PDF downloaded');return file;}catch(e){toast('PDF export failed: '+e.message);return null;}}
$('emailBtn').onclick=()=>{if(!weekSlots().length){toast('Add hours before preparing an email.');return;}const s=state.settings,sun=add(selected,6);$('mailFrom').value=s.sender||'';$('mailTo').value=s.recipient||'';$('mailBcc').value=s.bcc||'';$('mailSubject').value='Timesheet - '+(s.name||'Gradcon')+' - week ending '+fmt(sun,{day:'numeric',month:'long',year:'numeric'});$('mailBody').value='Hi Accounts,\n\nPlease find attached my timesheet for '+fmt(selected)+' to '+fmt(sun,{day:'numeric',month:'short',year:'numeric'})+'.\n\nTotal hours: '+dailyTotal(weekSlots()).toFixed(2)+'\nSubmission date: '+fmt(add(selected,8))+'\nPayment date: '+fmt(add(selected,9))+'\n\nKind regards,\n'+(s.name||'');$('emailDialog').showModal();};
$('mailDownload').onclick=downloadPdf;
$('emailForm').onsubmit=e=>{e.preventDefault();const fields=['mailFrom','mailTo','mailBcc','mailSubject'];if(fields.some(id=>/[\r\n]/.test($(id).value))){toast('Email headers must be a single line.');return;}const next=structuredClone(state);next.settings.sender=$('mailFrom').value.trim();next.settings.recipient=$('mailTo').value.trim();next.settings.bcc=$('mailBcc').value.trim();try{persist(next);}catch(error){toast(error.message);return;}const params=new URLSearchParams({authuser:$('mailFrom').value.trim(),view:'cm',fs:'1',to:$('mailTo').value.trim(),bcc:$('mailBcc').value.trim(),su:$('mailSubject').value,body:$('mailBody').value});window.open('https://mail.google.com/mail/?'+params.toString(),'_blank','noopener,noreferrer');toast('Attach the PDF in Gmail, check sender and BCC, then press Send.');};

function openHistory(){const records=[...(state.history||[])].reverse();const legacy=Object.keys(state.submitted).filter(w=>!records.some(h=>h.week===w));$('historyList').innerHTML=records.map(h=>'<article class="history-row"><div><strong>Week ending '+esc(fmt(add(parseDate(h.week),6),{day:'numeric',month:'short',year:'numeric'}))+'</strong><p>Marked submitted · Revision '+h.revision+'<br>'+esc(new Date(h.savedAt).toLocaleString('en-AU'))+'</p></div><div><button class="btn" data-history-week="'+esc(h.week)+'">Open week</button><button class="btn primary" data-history-pdf="'+esc(h.id)+'">Saved PDF</button></div></article>').join('')+legacy.map(w=>'<article class="history-row"><div><strong>Week ending '+esc(fmt(add(parseDate(w),6),{day:'numeric',month:'short',year:'numeric'}))+'</strong><p>Previously marked submitted · No saved PDF snapshot</p></div><button class="btn" data-history-week="'+esc(w)+'">Open week</button></article>').join('')||'<p>No submissions yet. Mark a completed week as submitted to save a PDF snapshot here.</p>';$('historyDialog').showModal();}
$('navHistory').onclick=openHistory;
$('historyList').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.historyWeek){selected=parseDate(b.dataset.historyWeek);render();$('historyDialog').close();}if(b.dataset.historyPdf){const h=state.history.find(h=>h.id===b.dataset.historyPdf);if(!h)return;try{const file=await createTimesheetPdf(h.snapshot,parseDate(h.week)),url=URL.createObjectURL(new Blob([file.bytes],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=file.filename.replace('.pdf','-revision-'+h.revision+'.pdf');a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(error){toast('Saved PDF could not be created: '+error.message);}}});
