import assert from 'node:assert/strict';
import {migrate,companySnapshot,switchCompany,parseDate,dailyTotal} from './dist/core.mjs';
import {submissionSchedule,isSubmissionDue,prepareSubmission} from './dist/automation.mjs';
const week=parseDate('2026-09-14');
const state=migrate(null);
state.entries['2026-09-14']=[{kind:'summary',manual:'7'}];
state.dayNotes['2026-09-14']='Private note';
state.history.push({snapshot:companySnapshot({...state,history:[]})});
state.companies.other={settings:{employer:'Other',sender:'other@example.com'},entries:{},submitted:{},dayNotes:{},dayNotesIncluded:{},history:[],scheduleOverrides:{}};
const other=switchCompany(state,'other');
assert.deepEqual(other.entries,{});
assert.equal(other.history.length,0);
const restored=switchCompany(other,'gradcon');
assert.equal(restored.entries['2026-09-14'][0].manual,'7');
restored.entries['2026-09-14'][0].manual='9';
assert.equal(restored.history[0].snapshot.entries['2026-09-14'][0].manual,'7');
assert.equal(restored.dayNotesIncluded['2026-09-14'],undefined);
assert.equal(prepareSubmission(state,week).usedFallback,false);
const empty=migrate(null),prepared=prepareSubmission(empty,week);
assert.equal(prepared.usedFallback,true);
assert.equal(dailyTotal(Object.values(prepared.state.entries).flat()),30);
assert.equal(Object.keys(empty.entries).length,0);
const schedule=submissionSchedule(empty,week);
assert.equal(schedule.date,'2026-09-22');
assert.equal(schedule.time,'23:00');
assert.equal(isSubmissionDue(schedule,new Date('2026-09-22T12:59:00Z')),false);
assert.equal(isSubmissionDue(schedule,new Date('2026-09-22T13:00:00Z')),true);
const summer={...schedule,date:'2026-12-22'};
assert.equal(isSubmissionDue(summer,new Date('2026-12-22T11:59:00Z')),false);
assert.equal(isSubmissionDue(summer,new Date('2026-12-22T12:00:00Z')),true);
empty.scheduleOverrides['2026-09-14']='2026-09-24';
assert.equal(submissionSchedule(empty,week).date,'2026-09-24');
console.log('PASS: employer isolation, immutable snapshots, private notes, 30-hour fallback, partial-week protection, date overrides, Melbourne daylight saving.');
